language: ruby
cache:
  directories:
    - vendor/bundle
sudo: false
rvm:
  - "2.3.3"
notifications:
  email: false
bundler_args: --without development:production --deployment --retry=3 --jobs=3
before_script:
  - bundle exec rake db:create
  - bundle exec rake db:migrate
before_install:
  - "export DISPLAY=:99.0"
script: bundle exec rake test
addons:
  postgresql: "9.3"
services:
  - redis-server
